### ISSUE TITLE
Meter returning a different value then when run directly in powershell

### ISSUE THREAD

**Issue by Wulf-Steppen** [khanhas/PowershellRM#1]
![Screenshot_1](https://user-images.githubusercontent.com/11824463/105576242-4dc79d00-5d26-11eb-800a-ade07a85f146.png)

Issue is pretty simple. I have a cmnd I can run natively in powershell that returns the index value of the current default audio device.  Running the cmnd through a meter returns a 0 instead of the expected value of 1 or 2.

**Comment by khanhas** [comment]
It's `Line2` not `Line 2`

**Comment by Wulf-Steppen** [comment]
I really need to quit working on things that late at night. Works great. Thanks for the quick response.
